registration/urls.py
from django.contrib import admin
from django.urls import path
from app1 import views
# from app1.views import SurveyRatingListView, SurveyRatingCreateView, SurveyRatingUpdateView, SurveyRatingDeleteView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.SignupPage, name='signup'),
    path('login/', views.LoginPage, name='login'),
    path('home/', views.HomePage, name='home'),
    path('logout/', views.LogoutPage, name='logout'),
    path('evaluation/', views.evaluation, name='evaluation'),
    path('evaluation/<int:pk>/edit/',
         views.edit_evaluation, name='edit_evaluation'),
    path('evaluation/<int:pk>/delete/',
         views.delete_evaluation, name='delete_evaluation'),
    path('evaluation_list/',
         views.evaluation_list, name='evaluation_list'),
]
#     path('survey-rating/list/', SurveyRatingListView.as_view(),
#          name='survey_rating_list'),
#     path('survey-rating/create/', SurveyRatingCreateView.as_view(),
#          name='survey_rating_create'),
#     path('survey-rating/<int:pk>/update/',
#          SurveyRatingUpdateView.as_view(), name='survey_rating_update'),
#     path('survey-rating/<int:pk>/delete/',
#          SurveyRatingDeleteView.as_view(), name='survey_rating_delete'),

app1/models.py
from django.db import models

# Create your models here.


# class SurveyRating(models.Model):
#     id = models.BigAutoField(primary_key=True)
#     course_objectives = models.IntegerField()
#     delivering_material = models.IntegerField()
#     engaging_students = models.IntegerField()
#     responding_questions = models.IntegerField()
#     providing_feedback = models.IntegerField()
#     inclusive_environment = models.IntegerField()
#     using_technology = models.IntegerField()
#     promoting_critical_thinking = models.IntegerField()
#     challenging_students = models.IntegerField()
#     overall_satisfaction = models.IntegerField()

# Create a model with a field to store the chosen option as an integer


class CourseEvaluation(models.Model):
    faculty_member = models.CharField(max_length=100)
    course_title = models.CharField(max_length=100)
    semester = models.CharField(max_length=100)
    year = models.IntegerField()
    evaluator = models.CharField(max_length=100)
    communication = models.IntegerField()
    delivery = models.IntegerField()
    engagement = models.IntegerField()
    responsiveness = models.IntegerField()
    feedback = models.IntegerField()
    inclusiveness = models.IntegerField()
    technology = models.IntegerField()
    critical_thinking = models.IntegerField()
    motivation = models.IntegerField()
    satisfaction = models.IntegerField()
    comments = models.CharField(max_length=200)

    @property
    def total_average(self):
        return sum([self.communication, self.delivery, self.engagement, self.responsiveness, self.feedback, self.inclusiveness, self.technology, self.critical_thinking, self.motivation, self.satisfaction]) / 10

    def __str__(self):
        return f"{self.course_title} - {self.faculty_member} ({self.semester} {self.year})"

app1/forms.py
from .models import CourseEvaluation
from django import forms
# from .models import SurveyRating


# class SurveyRatingForm(forms.ModelForm):
#     class Meta:
#         model = SurveyRating
#         fields = ['course_objectives', 'delivering_material', 'engaging_students',
#                   'responding_questions', 'providing_feedback', 'inclusive_environment',
#                   'using_technology', 'promoting_critical_thinking', 'challenging_students',
#                   'overall_satisfaction']


class CourseEvaluationForm(forms.ModelForm):
    communication = forms.TypedChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'),
                 (4, '4'), (5, '5')],
        widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
        coerce=int
    )
    delivery = forms.TypedChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'),
                 (4, '4'), (5, '5')],
        widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
        coerce=int
    )
    engagement = forms.TypedChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'),
                 (4, '4'), (5, '5')],
        widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
        coerce=int
    )
    responsiveness = forms.TypedChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'),
                 (4, '4'), (5, '5')],
        widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
        coerce=int
    )
    feedback = forms.TypedChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'),
                 (4, '4'), (5, '5')],
        widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
        coerce=int
    )
    inclusiveness = forms.TypedChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'),
                 (4, '4'), (5, '5')],
        widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
        coerce=int
    )
    technology = forms.TypedChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'),
                 (4, '4'), (5, '5')],
        widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
        coerce=int
    )
    critical_thinking = forms.TypedChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'),
                 (4, '4'), (5, '5')],
        widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
        coerce=int
    )
    motivation = forms.TypedChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'),
                 (4, '4'), (5, '5')],
        widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
        coerce=int
    )
    satisfaction = forms.TypedChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'),
                 (4, '4'), (5, '5')],
        widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
        coerce=int
    )

    class Meta:
        model = CourseEvaluation
        fields = ['faculty_member', 'course_title', 'semester', 'year', 'evaluator', 'communication', 'delivery', 'engagement', 'responsiveness',
                  'feedback', 'inclusiveness', 'technology', 'critical_thinking', 'motivation', 'satisfaction', 'comments']

app1/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from .models import CourseEvaluation
from .forms import CourseEvaluationForm
from django.shortcuts import render
# from .forms import SurveyRatingForm
from django.urls import reverse_lazy
# from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.views import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
# from .models import SurveyRating


@login_required(login_url='login')
def HomePage(request):
    return render(request, 'home.html')


def SignupPage(request):
    if request.method == 'POST':
        uname = request.POST.get('username')
        email = request.POST.get('email')
        pass1 = request.POST.get('password1')
        pass2 = request.POST.get('password2')

        if pass1 != pass2:
            return HttpResponse("Your password and confrom password are not Same!!")
        else:

            my_user = User.objects.create_user(uname, email, pass1)
            my_user.save()
            return redirect('login')
    return render(request, 'signup.html')

# Create your views here.


def LoginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        pass1 = request.POST.get('pass')
        user = authenticate(request, username=username, password=pass1)
        if user is not None:
            login(request, user)
            return redirect('evaluation_list')
        else:
            return HttpResponse("Username or Password is incorrect!!!")

    return render(request, 'login.html', {'user': request.user})


def LogoutPage(request):
    logout(request)
    return redirect('login')


# class SurveyRatingListView(ListView):
#     model = SurveyRating
#     template_name = 'survey_rating_list.html'
#     context_object_name = 'survey_ratings'


# class SurveyRatingCreateView(CreateView):
#     model = SurveyRating
#     fields = ['course_objectives', 'delivering_material', 'engaging_students', 'responding_questions', 'providing_feedback',
#               'inclusive_environment', 'using_technology', 'promoting_critical_thinking', 'challenging_students', 'overall_satisfaction']
#     template_name = 'survey_rating_form.html'
#     success_url = reverse_lazy('survey_rating_list')


# class SurveyRatingUpdateView(UpdateView):
#     model = SurveyRating
#     fields = ['course_objectives', 'delivering_material', 'engaging_students', 'responding_questions', 'providing_feedback',
#               'inclusive_environment', 'using_technology', 'promoting_critical_thinking', 'challenging_students', 'overall_satisfaction']
#     template_name = 'survey_rating_form.html'
#     success_url = reverse_lazy('survey_rating_list')


# class SurveyRatingDeleteView(DeleteView):
#     model = SurveyRating
#     template_name = 'survey_rating_confirm_delete.html'
#     success_url = reverse_lazy('survey_rating_list')


# def survey_rating(request):
#     if request.method == 'POST':
#         form = SurveyRatingForm(request.POST)
#         if form.is_valid():
#             form.save()
#     else:
#         form = SurveyRatingForm()
#     return render(request, 'survey_rating.html', {'form': form})


def evaluation(request):
    if request.method == 'POST':
        form = CourseEvaluationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('evaluation_list')
    else:
        form = CourseEvaluationForm()
    return render(request, 'evaluation.html', {'form': form})


def edit_evaluation(request, pk):
    template_name = 'evaluation.html'
    success_url = reverse_lazy('evaluation_list')
    evaluation = get_object_or_404(CourseEvaluation, pk=pk)
    if request.method == 'POST':
        form = CourseEvaluationForm(request.POST, instance=evaluation)
        if form.is_valid():
            form.save()
            return redirect('evaluation_list')
    else:
        form = CourseEvaluationForm(instance=evaluation)
    return render(request, template_name, {'form': form})


def delete_evaluation(request, pk):
    template_name = 'delete_evaluation.html'
    success_url = reverse_lazy('survey_rating_list')
    evaluation = get_object_or_404(CourseEvaluation, pk=pk)
    if request.method == 'POST':
        evaluation.delete()
        return redirect('evaluation_list')
    return render(request, template_name, {'evaluation_list': evaluation})


def evaluation_list(request):
    evaluations = CourseEvaluation.objects.all()
    return render(request, 'evaluation_list.html', {'evaluations': evaluations})

app1/templates/delete_evaluation.html
{% extends 'home.html' %}

{% block content %}
<style>
    .delbtn{
        
    }
</style>
  <h1>Confirm Delete</h1>
  <p>Are you sure you want to delete this survey rating?</p>
  <form method="post">
    {% csrf_token %}
    <input class = "delbtn" type="submit" value="Yes, delete">
    <a href="{% url 'evaluation_list' %}">Cancel</a>
  </form>
{% endblock %}

app1/templates/evaluation.html
{% extends 'home.html' %}
<style>
   .radio-inline input[type="radio"] {
      margin-top: -1px;
      vertical-align: middle;
      grid-column: 1 / span 2;
  }
</style>
{% load static %}
{% block content %}
<div class="container">
    <div>
        <h3><a href="{% url 'evaluation_list' %}" style="color:#fff;" >Survey rating list</a></h3>
     </div>
     
     <hr>
     <img src="{% static 'images/ksuniversity.png' %}" alt="lol" style="width: 125px;">
    <h3>KSU Faculty Evaluation Survey</h3>
  <hr>
  <form method="post">
    {% csrf_token %}
    <div class= 'rating-container'>
        <label for="id_faculty_member">Faculty member:</label>
        {{form.faculty_member}}
    </div>
    <div class= 'rating-container'>
        <label for="id_course_title">Course title:</label>
        {{form.course_title}}
    </div>
    <div class= 'rating-container'>
        <label for="id_semester">Semester:</label>
        {{form.semester}}
    </div>
    <hr>
    <div class= 'rating-container'>
        <label for="id_year">Year:</label>
        {{form.year}}
    </div>
    <br>
    <h5>When rating these questions, you could use a scale from 1-5, with 1 being the lowest rating and 5 being the highest rating.</h5>
    <div class= 'rating-container'>
        <label for="id_evaluator">Evaluator:</label>
        {{form.evaluator}}
    </div>
    <hr>
    <br>
    <p>1. How well did the faculty member communicate the course objectives and expectations at the beginning of the course?</p>
     <div>
      {% for radio in form.communication %}
            {{ radio }}
          {% endfor %}
    {% comment %} {{form.communication}} {% endcomment %}
     </div>
     <p>2. How effective was the faculty member in delivering the course material and explaining complex concepts?</p>
     <div>
      {% for radio in form.delivery %}
            {{ radio }}
          {% endfor %}
        {% comment %} {{form.delivery}} {% endcomment %}
     </div>
     <p>3.How well did the faculty member engage with the students during the course?</p>
     <div>
      {% for radio in form.engagement %}
            {{ radio }}
          {% endfor %}
        {% comment %} {{form.engagement}} {% endcomment %}
     </div>
     <p>4.Did the faculty member respond to student questions and concerns in a timely manner?</p>
     <div>
      {% for radio in form.responsiveness %}
            {{ radio }}
          {% endfor %}
        {% comment %} {{form.responsiveness}} {% endcomment %}
     </div>
     <p>5.Did the faculty member provide helpful feedback on assignments and exams in a timely manner?</p>
     <div>
      {% for radio in form.feedback %}
            {{ radio }}
          {% endfor %}
        {% comment %} {{form.feedback}} {% endcomment %}
     </div>
     <p>6.Did the faculty member create a welcoming and inclusive classroom environment?</p>
     <div>
      {% for radio in form.inclusiveness %}
            {{ radio }}
          {% endfor %}
        {% comment %} {{form.inclusiveness}} {% endcomment %}
     </div>
     <p>7. Did the faculty member effectively use technology in the course?</p>
     <div>
      {% for radio in form.technology %}
            {{ radio }}
          {% endfor %}
        {% comment %} {{form.technology}} {% endcomment %}
     </div>
     <p>8. Did the faculty member promote critical thinking and intellectual curiosity among students?</p>
     <div>
      {% for radio in form.critical_thinking %}
            {{ radio }}
          {% endfor %}
        {% comment %} {{form.critical_thinking}} {% endcomment %}
     </div>
     <p>9. Did the faculty member effectively challenge and motivate students to learn?</p>
     <div>
      {% for radio in form.motivation %}
            {{ radio }}
          {% endfor %}
        {% comment %} {{form.motivation}} {% endcomment %}
     </div>
     <p>10. Overall, how satisfied were you with the faculty member's performance in the course?</p>
     <div>
      {% for radio in form.satisfaction %}
            {{ radio }}
          {% endfor %} {% comment %} note: this for loop displays radio button horizontally {% comment %}
        {% comment %} {{form.satisfaction}} {% endcomment %}
     </div>
     <hr>
     &nbsp
     <div class= 'rating-container'>
        <p><label for="id_comments">Comments:</label></p>
        {{form.comments}}
     </div>
    <button style="color:white; border-radius:10%; background-color: black;" type="submit">Submit</button>
  </form>
</div>
{% endblock %}

app1/templates/evaluation_list.html
{% extends 'home.html' %}
{%block content %}
<style>
  .table-container{
    border-collapse: collapse;
    width: 95rem;
    margin:1.5rem;
  }
    table {
        border-collapse: collapse;
        width: 45rem;
      }
      
      th,
      td {
        border: 1px solid white;
        padding: 8px;
        text-align: left;
        color: #ffff;
      }
      .table-container {
        overflow-x: auto;
        overflow-y: auto;
      }
    th {
      background-color: #4CAF50;
    }
    tr:nth-child(even) {
      background-color: #4CAF50;
    }
    @media screen and (max-width: 12rem) {
        table {  
          width: 25%;
            margin-left:4rem;
          }
       
      th, td {
        display: inline-block;
      }
      th {
        text-align: center;
        background-color: #4CAF50;
        color: #fff;
        font-size: 16px;
        padding: 10px;
      }
      td {
        border-bottom: 1px solid #ddd;
      }
      td::before {
        content: attr(data-label);
        float: left;
        font-weight: bold;
        text-transform: uppercase;
      }
    }
</style>
<center><h3><a style="color:#fff;" href="{% url 'evaluation' %}">Add new faculty rating</a></h3></center>
  <hr>
  <center><div>
    <table>
        <thead>
          <tr>
            <th>Scale</th>
            <th>Descriptive Rating</th>
            <th>Qualitative Description</th>
            </tr>
        </thead>
        <tbody> 
              <tr>
                <td>5</td>
                <td>Outstanding</td>
                <td>Performance is exceptional</td>
              </tr>
              <tr>
                <td>4</td>
                <td>Very Satisfactory</td>
                <td>Performance always exceeds the requirements</td>
              </tr>
              <tr>
                <td>3</td>
                <td>Satisfactory</td>
                <td>Performance meets the requirements</td>
              </tr>
              <tr>
                <td>2</td>
                <td>Fair</td>
                <td>Performance need some enhancement to meet job requirements</td>
              </tr>
              <tr>
                <td>1</td>
                <td>Poor</td>
                <td>Performance failed to meet job requirements</td>
              </tr>
        </tbody>
    </table>
</div></center>
<hr>
<br>
<center><h4>Faculty Evaluations</h4></center>
<div class="table-container">
    <table>
      <thead>
        <tr>
          <th>Faculty</th>
          <th>Course Title</th>
          <th>Semester</th>
          <th>Year</th>
          <th>Evaluator</th>
          <th>Course Objectives</th>
          <th>Delivering Material</th>
          <th>Engaging Students</th>
          <th>Responding Questions</th>
          <th>Providing Feedback</th>
          <th>Inclusive Environment</th>
          <th>Using Technology</th>
          <th>Promoting Critical Thinking</th>
          <th>Challenging Students</th>
          <th>Satisfaction</th>
          <th>Comments</th>
          <th>Total Average</th>
          <th>Actions</th>
          
        </tr>
      </thead>
      <tbody>
        {% for evaluation in evaluations %}
          <tr>
            <td>{{ evaluation.faculty_member }}</td>
            <td>{{ evaluation.course_title }}</td>
            <td>{{ evaluation.semester }}</td>
            <td>{{ evaluation.year }}</td>
            <td>{{ evaluation.evaluator }}</td>
            <td>{{ evaluation.communication }}</td>
            <td>{{ evaluation.delivery }}</td>
            <td>{{ evaluation.engagement }}</td>
            <td>{{ evaluation.responsiveness }}</td>
            <td>{{ evaluation.feedback }}</td>
            <td>{{ evaluation.inclusiveness }}</td>
            <td>{{ evaluation.technology }}</td>
            <td>{{ evaluation.critical_thinking }}</td>
            <td>{{ evaluation.motivation }}</td>
            <td>{{ evaluation.satisfaction }}</td>
            <td>{{ evaluation.comments }}</td>
            <td>{{ evaluation.total_average }}</td>
            <td>
              <div><a style="color:white;" href="{% url 'edit_evaluation' evaluation.pk %}">Edit</a></div>
              <form method="post" action="{% url 'delete_evaluation' evaluation.pk %}" id="delete-form">
                {% csrf_token %}
                <input type="button" value="Delete" onclick="showConfirm()">
            </form>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="11">No survey ratings yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>  
</div>
<script>
  function showConfirm() {
      if (confirm("Are you sure you want to delete this evaluation?")) {
          document.getElementById("delete-form").submit();
      } else {
          return false;
      }
  }
</script>
{% endblock %}

app1/templates/home.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/survey.css' %}">
  </head>
  <body>
    <div>
      <br>
      {% if user.is_authenticated %}
      Welcome, {{ request.user.username }}!
      {% endif %}
      <br>
      </div>
      <br>
    <a href="{% url 'logout' %}" class="btn btn-primary">Logout</a>
    <hr>
    
  {% block content %}


   {% endblock %}
  </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    {% comment %} <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> {% endcomment %}
  </body>
</html>

app1/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}LoginPage{% endblock %}
 
    {% comment %} <link rel="preconnect" href="https://fonts.gstatic.com"> {% endcomment %}
    {% comment %} <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/login.css'%}">

</head>
<body class="body" style="background-color:rgba(6, 124, 139, 0.808);">
    <form method="post">
        <h3>Login Here</h3>
        {% csrf_token %} 
        <label for="username">Username</label>
        <input type="text" placeholder="Enter Username" id="username" name="username">

        <label for="password">Password</label>
        <input type="password" placeholder="Password" id="password" name="pass">

        <button type="submit">Log In</button>
        <a href="{% url 'signup' %}" >Create an account</a>
    </form>
</body>
</html>

app1/templates/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    {% block title %}SignupPage{% endblock %}
 
    {% comment %} <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"> {% endcomment %}
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/signuppage.css'%}">
    <!--Stylesheet-->
</head>
<body class="body" style="background-color:rgba(6, 124, 139, 0.808);">
    {% comment %} <div class="background">
        <img id='iamg' src="{% static 'images/ksuniversity.png' %}" alt="ksupic">
    </div> {% endcomment %}
    <form class="forms" action="" method="post">
        {% csrf_token %} 
        <h3>Signup Here</h3>

        <label for="username">Username</label>
        <input type="text" placeholder="Username" name="username" id="username">

        <label for="email">Email</label>
        <input type="email" placeholder="Email or Phone" name="email" id="email">

        <label for="password1">Password</label>
        <input type="password" placeholder="Password" id="password1" name="password1">

        <label for="password2">Confirm Password</label>
        <input type="password" placeholder="Confirm Password" id="password2" name="password2">
        <button type="submit">Signup</button>
        <a href="{% url 'login' %}" >I have already an account</a>
   
    </form>

</body>
</html>

app1/templates/survey_rating_confirm_delete.html
{% extends 'home.html' %}

{% block content %}
<style>
    .delbtn{
        
    }
</style>
  <h1>Confirm Delete</h1>
  <p>Are you sure you want to delete this survey rating?</p>
  <form method="post">
    {% csrf_token %}
    <input class = "delbtn" type="submit" value="Yes, delete">
    <a href="{% url 'survey_rating_list' %}">Cancel</a>
  </form>
{% endblock %}

app1/templates/survey_rating_list.html
{% extends 'home.html' %}

{% block content %}
<style>
    .table-container {
        overflow-x: auto;
        overflow-y: auto;
      }
    table {
      border-collapse: collapse;
      width: 65%;
      margin-left:12rem;
    }
    th, td {
      text-align: left;
      padding: 8px;
      
    }
    th {
      background-color: #4CAF50;
    }
    tr:nth-child(even) {
      background-color: #4CAF50;
    }
    @media screen and (max-width: 12rem) {
        table {  
          width: 25%;
            margin-left:4rem;
          }
       
      th, td {
        display: inline-block;
      }
      th {
        text-align: center;
        background-color: #4CAF50;
        color: #fff;
        font-size: 16px;
        padding: 10px;
      }
      td {
        border-bottom: 1px solid #ddd;
      }
      td::before {
        content: attr(data-label);
        float: left;
        font-weight: bold;
        text-transform: uppercase;
      }
    }
  </style>
  <a style="color:#fff;" href="{% url 'survey_rating_create' %}">Add new survey rating</a>
  <hr>
  <center><h1>KSU FACULTY EVALUATION SYSTEM</h1>
  </center>
  
  <div class="table-container">
    <table>
      <thead>
        <tr>
          <th>Course Objectives</th>
          <th>Delivering Material</th>
          <th>Engaging Students</th>
          <th>Responding Questions</th>
          <th>Providing Feedback</th>
          <th>Inclusive Environment</th>
          <th>Using Technology</th>
          <th>Promoting Critical Thinking</th>
          <th>Challenging Students</th>
          <th>Overall Satisfaction</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for survey_rating in survey_ratings %}
          <tr>
            <td>{{ survey_rating.course_objectives }}</td>
            <td>{{ survey_rating.delivering_material }}</td>
            <td>{{ survey_rating.engaging_students }}</td>
            <td>{{ survey_rating.responding_questions }}</td>
            <td>{{ survey_rating.providing_feedback }}</td>
            <td>{{ survey_rating.inclusive_environment }}</td>
            <td>{{ survey_rating.using_technology }}</td>
            <td>{{ survey_rating.promoting_critical_thinking }}</td>
            <td>{{ survey_rating.challenging_students }}</td>
            <td>{{ survey_rating.overall_satisfaction }}</td>
            <td>
              <a href="{% url 'survey_rating_update' survey_rating.pk %}">Edit</a>
              <form method="post" action="{% url 'survey_rating_delete' survey_rating.pk %}">
                {% csrf_token %}
                <input type="submit" value="Delete">
              </form>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="12">No survey ratings yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    
  </div>
{% endblock %}